language: perl
perl:
  - "5.20"
  - "5.18"
before_install:
  - cpanm Carton
  - cpanm -n Devel::Cover::Report::Coveralls
install:
  - carton install
  - cp config/development.pl.sample config/development.pl
  - sqlite3 db/sample.db < sql/sqlite.sql
  - carton exec perl t/Util.pm
script:
  - PERL5OPT='-MDevel::Cover=-db,./cover_db' carton exec prove -lrv t && carton exec cover -ignore_re "^local/" -report coveralls
notifications:
  email:
    recipients:
      - celeron1ghz@gmail.com
    on_success: change
    on_failure: always
  slack:
    secure: tAocD6UkdIie5bNkaBBEQvk0fqeZI86vhykJE0bpdNty5PYV+IGKJBSoQTWoup/TNMaZszF6RP3tcC8VrIR/1RE9lld1Z178RncvH2wopRmzwBSqzcRMLvDRmY8Vaz+w4TdljlA2t8lFbEP0WDgSiwnInmde727ao8fJbbC1CXw=
