language: perl
perl:
  - "5.20"
  - "5.18"

before_install:
  - cpanm Carton
install:
  - carton install
  - cp config/config_sample.pl config/development.pl
  - sqlite3 sample.db < CREATE.sql
script:
  - carton exec prove -lrv t

notifications:
  email:
    recipients:
      - celeron1ghz@gmail.com
    on_success: change
    on_failure: always
