language: perl
perl:
  - "5.20"
  - "5.18"

before_install:
  - cpanm Carton
  - cpanm -n Devel::Cover::Report::Coveralls
install:
  - carton install
  - cp config/config_sample.pl config/development.pl
  - sqlite3 sample.db < CREATE.sql
script:
  - PERL5OPT='-MDevel::Cover=-db,./cover_db' carton exec prove -lrv t && carton exec cover -ignore_re "^local/" -report coveralls

notifications:
  email:
    recipients:
      - celeron1ghz@gmail.com
    on_success: change
    on_failure: always
